id: IE51BDEBB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T13:49:19+00:00'
last_modified: '2022-06-08T02:32:55.736314+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17647
  title: རྒྱ་ནག་གླང་ཆེན་འགྱིང་རིའི་གནས་ཡིག་དད་ལྡན་སྐྱིད་པའི་ཕོ་ཉ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    D0AD:
      image_group_id: I2PD19251
      title: ''
      total_pages: 102
      order: 1
      base_file: D0AD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
