id: P005362
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17647
  title: རྒྱ་ནག་གླང་ཆེན་འགྱིང་རིའི་གནས་ཡིག་དད་ལྡན་སྐྱིད་པའི་ཕོ་ཉ།
  author: ''
  volumes:
    5a4c6a9a3a024214a67bdfc8cc3dda46:
      image_group_id: I2PD19251
      title: ''
      volume_number: 1
      total_pages: 102
